### PR TITLE
Add Statement methods

### PR DESCRIPTION
**Pull request by RyanSpittler**
- Allows methods to check if a Statement has been returned.
- Refactored methods for ease of reuse.

### CODE REVIEW

**Comment by RyanSpittler** [comment]
@bradley2W1DL Here's the simple refactor.

**Review by bradley2W1DL — APPROVED** [review]
👍  this looks good to me

**Review by bjacobso — COMMENTED** [review]
LGTM

**Comment by kcbigring** [comment]
dude... you move to SV and START to use all that slang... LGTM???

i see. looks good to me ;)

hope you are good @bjacobso 

GTG

**Pull request merged**
